export type DevicePresenceStatus =
  | "online"
  | "offline";

export const DEVICE_ONLINE_WINDOW_MS =
  2 * 60 * 1000;

type LastSeenAt =
  | Date
  | string
  | null
  | undefined;

export const deriveDeviceStatus = (
  lastSeenAt: LastSeenAt,
  now: Date = new Date(),
  onlineWindowMs:
    number =
      DEVICE_ONLINE_WINDOW_MS
): DevicePresenceStatus => {
  if (
    !Number.isFinite(
      onlineWindowMs
    ) ||
    onlineWindowMs <= 0
  ) {
    throw new Error(
      "onlineWindowMs must be a positive finite number"
    );
  }

  if (!lastSeenAt) {
    return "offline";
  }

  const lastSeenMs =
    lastSeenAt instanceof Date
      ? lastSeenAt.getTime()
      : new Date(
          lastSeenAt
        ).getTime();

  const nowMs =
    now.getTime();

  if (
    !Number.isFinite(
      lastSeenMs
    ) ||
    !Number.isFinite(
      nowMs
    )
  ) {
    return "offline";
  }

  const ageMs =
    nowMs -
    lastSeenMs;

  // lastSeenAt is generated by the server.
  // A timestamp in the future is treated
  // fail-closed as offline.
  if (ageMs < 0) {
    return "offline";
  }

  return ageMs <=
    onlineWindowMs
    ? "online"
    : "offline";
};

export const withDerivedDevicePresence =
  <
    T extends {
      lastSeenAt?:
        LastSeenAt;
    }
  >(
    device: T,
    now: Date = new Date()
  ): T & {
    status:
      DevicePresenceStatus;
  } => {
    return {
      ...device,
      status:
        deriveDeviceStatus(
          device.lastSeenAt,
          now
        ),
    };
  };
